GET http://localhost:3000/user-api/users

###

POST http://localhost:3000/user-api/users
Content-Type: application/json

{
    "id":2,
    "name":"Dinesh",
    "age":20
}

###

PUT http://localhost:3000/user-api/users
Content-Type: application/json

{
    "id":1,
    "name":"Dinesh Karthik",
    "age":35
}

###

GET http://localhost:3000/user-api/users/2

###

DELETE http://localhost:3000/user-api/users/1


###
GET http://localhost:3000/products-api/products

###
POST http://localhost:3000/products-api/products
Content-Type: application/json

{
    "productId": 2,
    "name":"Redmi Note 10",
    "price":30000,
    "brand":"MI"
}

###

PUT http://localhost:3000/products-api/products
Content-Type: application/json

{
    "productId":2,
    "name": "Vivo y50",
    "price":20000,
    "brand":"VIVO"

}
###

GET http://localhost:3000/products-api/products/1